Models/Drawing.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DrawingsWebApp.Models
{
    public class Drawing
    {
        [Key] 
        public int Id { get; set; }
        [Required]
        [Display(Name = "Name")]
        public string FileName { get; set; }
        public string Comment { get; set; } = "";
        public string CommentDateTime { get; set; } = "";
        [Required]
        public byte[] Image { get; set; }
        public DateTime UploadedDateTime { get; set; } = DateTime.Now;
        [NotMapped]
        [Display(Name = "Drawing File")]
        public IFormFile FormImage { get; set; }
        [NotMapped]
        [Display(Name = "Comment")]
        public string FormComment { get; set; }
        [NotMapped]
        public DateTime FormCommentDateTime { get; set; } = DateTime.Now;

    }
}

Models/ErrorViewModel.cs
namespace DrawingsWebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/FormModel.cs
namespace DrawingsWebApp.Models
{
    public class FormModel
    {
        public UserModes currentUserMode { get; set; }
    }

    public enum UserModes
    {
        engineer, writer
    }
    
}

Models/UserModeModel.cs
namespace DrawingsWebApp.Models
{
    public class UserModeModel
    {
        
    }
}

Controllers/DrawingController.cs
using DrawingsWebApp.Data;
using DrawingsWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Web;

namespace DrawingsWebApp.Controllers
{
    public class DrawingController : Controller
    {
        private readonly ApplicationDbContext _db;

        public DrawingController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Drawing> objDrawingList = _db.Drawings.ToList();
            return View(objDrawingList);
        }

        public IActionResult RenderImage(int id)
        {
            Drawing drawing = _db.Drawings.Find(id);
            byte[] byteData = drawing.Image;
            return File(byteData, "image/png");
        }

        public IActionResult DetailedView(int? id)
        {
            if (id == null || id.Value == 0)
            {
                return NotFound();
            }
            var drawingFromDb = _db.Drawings.Find(id);

            if (drawingFromDb == null)
            {
                return NotFound();
            }

            return View(drawingFromDb);
        }

        //GET
        public IActionResult CreateComment(int? id)
        {
            if (id == null || id.Value == 0)
            {
                return NotFound();
            }
            var drawingFromDb = _db.Drawings.Find(id);

            if (drawingFromDb == null)
            {
                return NotFound();
            }

            return View(drawingFromDb);
        }
         
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateComment(Drawing model, string commentString, string dateTimeString)
        {
            if (commentString == null)
            {
                model.Comment = model.FormComment;
                model.CommentDateTime = model.FormCommentDateTime.ToString();
            } 
            else
            {
                string[] comments = commentString.Split("@#$%&");
                string[] dateTimes = dateTimeString.Split("@#$%&");
                string[] updatedComments = new string[comments.Length + 1];
                string[] updatedDateTimes = new string[dateTimes.Length + 1];
                for (int i = 0; i < comments.Length; i++)
                {
                    updatedComments[i] = comments[i];
                    updatedDateTimes[i] = dateTimes[i];
                }
                updatedComments[updatedComments.Length - 1] = model.FormComment;
                updatedDateTimes[updatedDateTimes.Length - 1] = model.FormCommentDateTime.ToString();
                model.Comment = String.Join("@#$%&", updatedComments);
                model.CommentDateTime = String.Join("@#$%&", updatedDateTimes);
            }
            _db.Drawings.Attach(model);
            _db.Entry(model).Property(x => x.Comment).IsModified = true;
            _db.Entry(model).Property(x => x.CommentDateTime).IsModified = true;
            _db.SaveChanges();
            TempData["success"] = "Comment added successfully";

            return RedirectToAction("DetailedView", new { id = model.Id});
        }

        //GET
        public IActionResult Upload()
        {
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upload(Drawing model)
        {

            //Convert the image into bytes array type
            using (MemoryStream ms = new MemoryStream())
            {
                await model.FormImage.CopyToAsync(ms);
                model.Image = ms.ToArray();
            }

            //Add to database
            _db.Drawings.Add(model);
            await _db.SaveChangesAsync();
            TempData["success"] = "Drawing uploaded successfully";

            return RedirectToAction("Index");

        }

        //GET
        public IActionResult Edit(int? id)
        {
            if(id==null || id.Value == 0)
            {
                return NotFound();
            }
            var drawingFromDb = _db.Drawings.Find(id);

            if (drawingFromDb == null)
            {
                return NotFound();
            }

            return View(drawingFromDb);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Drawing model)
        {
            _db.Drawings.Attach(model);
            _db.Entry(model).Property(x => x.FileName).IsModified = true;
            _db.SaveChanges();
            TempData["success"] = "Drawing name updated successfully";

            return RedirectToAction("Index");

        }

        //GET
        public IActionResult Delete(int? id)
        {
            if (id == null || id.Value == 0)
            {
                return NotFound();
            }
            var drawingFromDb = _db.Drawings.Find(id);

            if (drawingFromDb == null)
            {
                return NotFound();
            }

            return View(drawingFromDb);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var model = _db.Drawings.Find(id);
            if (model == null)
            {
                return NotFound();
            }
            _db.Drawings.Remove(model);
            _db.SaveChanges();
            TempData["success"] = "Drawing deleted successfully";

            return RedirectToAction("Index");

        }

    }
}

Controllers/HomeController.cs
using DrawingsWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace DrawingsWebApp.Controllers
{
    public class HomeController : Controller
    {

        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            ViewBag.UserModes = "engineer";
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }


        [HttpPost]
        public IActionResult Index(FormModel myForm)
        {
            var selectedValue = myForm.currentUserMode;
            ViewBag.UserModes = selectedValue.ToString();
            return View();
        }


        
    }
}

Views/Drawing/CreateComment.cshtml
@model Drawing
@{
    string commentString = Model.Comment;
    string dateTimeString = Model.CommentDateTime;
}

<form method="post" asp-action="CreateComment" asp-route-commentString="@commentString" asp-route-dateTimeString="@dateTimeString">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="test-primary">Create Comment</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="FormComment"></label>
            <input asp-for="FormComment" class="form-control" />
            <span asp-validation-for="FormComment" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Add Comment</button>
        <a asp-controller="Drawing" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to Drawings
        </a>
    </div>
</form>

@section Scripts{
    @{ 
        <partial name="_ValidationScriptsPartial" />
    }
}

Views/Drawing/Delete.cshtml
@model Drawing

<form method="post" asp-action="DeletePOST">
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="test-primary">Delete Drawing</h2>
            <hr />
        </div>
        <div class="mb-3">
            <h5 class="">Are you sure you want to delete @Model.FileName?</h5>
        </div>
        <div class="mb-3">
            <img width="100%" src="@Url.Action("RenderImage", new { id = Model.Id })" />
        </div>
        <button type="submit" class="btn btn-danger" style="width:150px">Confirm Delete</button>
        <a asp-controller="Drawing" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to Drawings
        </a>
    </div>
</form>

@section Scripts{
    @{ 
        <partial name="_ValidationScriptsPartial" />
    }
}

Views/Drawing/DetailedView.cshtml
@model Drawing

<div class="border p-3 mt-4">
    <div class="row pb-2">
        <h2 class="test-primary">Detailed View</h2>
        <hr />
    </div>
    <div class="mb-3">
        <img width="100%" src="@Url.Action("RenderImage", new { id = Model.Id })" />
    </div>
    <a asp-controller="Drawing" asp-action="Index" class="btn btn-secondary" style="width:150px">
        Back to Drawings
    </a>
</div>
<br />
<div class="border p-3 mt-4"> 
    <a asp-controller="Drawing" asp-action="CreateComment" asp-route-id="@Model.Id"
    class="btn btn-primary mx-2"><i class="bi bi-plus-circle"></i> Add a comment</a>
    <hr />
    <table class="table table-bordered table-striped" style="width:100%">   
    <thead>
        <tr>
            <th>
                Comments
            </th>
            <th>
                Date and Time Posted
            </th>
        </tr>
    </thead>
    <tbody>
        @{
            string[] comments = Model.Comment.Split("@#$%&");
            string[] dateTimes = Model.CommentDateTime.Split("@#$%&");
        }
        @for(int i = 0; i < comments.Length; i++)
        {
            <tr>
                <td>
                    @comments[i]
                </td>
                <td width="20%">
                    @dateTimes[i]
                </td>
                
            </tr>
        }
    </tbody>
</table>

</div>

@section Scripts{
    @{ 
    <partial name="_ValidationScriptsPartial" />
    }
}

Views/Drawing/Edit.cshtml
@model Drawing

<form method="post" asp-action="Edit">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="test-primary">Edit Name</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="FileName"></label>
            <input asp-for="FileName" class="form-control" />
            <span asp-validation-for="FileName" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Save Changes</button>
        <a asp-controller="Drawing" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to Drawings
        </a>
    </div>
</form>

@section Scripts{
    @{ 
        <partial name="_ValidationScriptsPartial" />
    }
}

Views/Drawing/Index.cshtml
@model IEnumerable<Drawing>
@{
    ViewData["Title"] = "Index";
}

<div class ="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Drawings</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Drawing" asp-action="Upload" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> &nbsp; Upload Drawing
            </a>
        </div>
    </div>
</div>

<table class="table table-bordered table-striped" style="width:100%">   
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Image
            </th>
            <th>
                Date and Time Uploaded
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach(var obj in Model)
        {
            <tr>
                <td width="20%">
                    @obj.FileName
                </td>
                <td>
                    <img height="100" src="@Url.Action("RenderImage", new { id = obj.Id })" />
                </td>
                <td width="20%">
                    @obj.UploadedDateTime
                </td>
                <td width="25%">
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="Drawing" asp-action="Edit" asp-route-id="@obj.Id"
                        class="btn btn-primary mx-2"><i class="bi bi-pencil-square"></i> Edit Name</a>
                        <a asp-controller="Drawing" asp-action="Delete" asp-route-id="@obj.Id"
                        class="btn btn-danger mx-2"><i class="bi bi-trash-fill"></i> Delete</a>
                        <a asp-controller="Drawing" asp-action="DetailedView" asp-route-id="@obj.Id"
                        class="btn btn-secondary mx-2"><i class="bi bi-search"></i> Detailed View</a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Drawing/Upload.cshtml
@model Drawing

<form method="post" enctype="multipart/form-data" asp-action="Upload">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="test-primary">Upload Drawing</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="FileName"></label>
            <input asp-for="FileName" class="form-control" />
            <span asp-validation-for="FileName" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="FormImage"></label>
            <input asp-for="FormImage" class="form-control" type="file" />
            <span asp-validation-for="FormImage" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Upload</button>
        <a asp-controller="Drawing" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to Drawings
        </a>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@model FormModel

<div id="UserModeForm">
                                
        @using (Html.BeginForm("Index","Home",FormMethod.Post))
        {
            @Html.DropDownList("currentUserMode",new SelectList(Enum.GetValues(typeof(UserModes))), new { @onchange = @"form.submit();"})
        }
    </div>
    <p>You are currently in @ViewBag.UserModes mode</p>


<div class="text-center">
    
    <table class="table">
        <thead>
            <tr>
                <th>Image Preview</th>
                <th>Image Title</th>
                <th>Comments</th>
                <th>Edit Button</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    
                    <button type="button" id="image1button" >
                        <img src=https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fpurepng.com%2Fpublic%2Fuploads%2Flarge%2Fpurepng.com-eaglebirdsflyanimals-631522936787gghpi.png&f=1&nofb=1 height="50" width="50"/>
                    </button>
                </td>
                <td>
                    image name
                </td>
                <td>
                    image comments
                </td>
                <td>
                    edit button
                </td>
            </tr>
        </tbody>
    </table>
    
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DrawingsWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DrawingsWebApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <img height="50" class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" src="https://imgs.search.brave.com/ZYTGUf9F_YbLTlGqzN3kH6srHLk8IT3NVs7PBB27QYQ/rs:fit:1200:1200:1/g:ce/aHR0cDovL3d3dy5w/bmdwaXguY29tL3dw/LWNvbnRlbnQvdXBs/b2Fkcy8yMDE2LzA3/L1BOR1BJWC1DT00t/Qm9laW5nLUxvZ28t/UE5HLVRyYW5zcGFy/ZW50LnBuZw" />
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Drawing" asp-action="Index">Drawings</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link text-dark dropdown-toggle" id="roleSelect" href="#" data-bs-toggle="dropdown" role="button" aria-expanded="false">
                                Role Select
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="roleSelect">
                                <li><a class="dropdown-item" href="#">Engineer</a></li>
                                <li><a class="dropdown-item" href="#">Writer</a></li>
                            </ul>
                        </li>
                        <li>
                            @Html.DropDownListFor(m => m.currentUserMode,
                                new SelectList(Enum.GetValues(typeof()
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - DrawingsWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Notification.cshtml
@if(TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}

@if(TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}